INSERT INTO category (name) VALUES ('American');
INSERT INTO category (name) VALUES ('Italian');
INSERT INTO category (name) VALUES ('Mexican');
INSERT INTO category (name) VALUES ('Fast Food');
INSERT INTO category (name) VALUES ('Good Belgian Cooking');
INSERT INTO unit_of_measure (name, unit) VALUES ('Teaspoon', 'Teaspoon');
INSERT INTO unit_of_measure (name, unit) VALUES ('Tablespoon', 'Tablespoon');
INSERT INTO unit_of_measure (name, unit) VALUES ('Cup', 'Cup');
INSERT INTO unit_of_measure (name, unit) VALUES ('Pinch', 'Pinch');
INSERT INTO unit_of_measure (name, unit) VALUES ('Ounce', 'oz');
INSERT INTO unit_of_measure (name, unit) VALUES ('Drop', 'Drop');
INSERT INTO unit_of_measure (name, unit) VALUES ('Kilogram', 'kg');
INSERT INTO unit_of_measure (name, unit) VALUES ('Gram', 'g');
INSERT INTO unit_of_measure (name, unit) VALUES ('Liter', 'l');
INSERT INTO unit_of_measure (name, unit) VALUES ('Milliliter', 'ml');