# Orb 'circleci/maven@0.0.12' resolved to 'circleci/maven@0.0.12'
version: 2
jobs:
  maven/test:
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline --settings 'pom.xml' cobertura:cobertura
      - run:
          name: Run Tests
          command: mvn verify --settings 'pom.xml'
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: target/surefire-reports
      - run:
          name: Send to CodeCov (this basically pings CodeCov and they will use a call back to investigate the contents of that folder)
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  maven_test:
    jobs:
      - maven/test
  version: 2